# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e26971fc66e0db93ec5bfe2bcf8bbc1c3d8f48460bb47ae3a3bd31e79d6b6296c157788a998825fb70624ed3f67b1bf447f75f17542e0fa1255f872614a5137f

test:
  secret_key_base: 132fe372a979f58186a8518ccfcd7ea9d89bb9ba252a4cbceb3989ece400465db6dabd4e71cff0e6ff55a25019b338231611e5372c6c2d33b020f1ce78f2a723

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
